### ISSUE TITLE
Improvement of Profile Page.

### ISSUE THREAD

**Issue by mjkoder** [manjit-hub/Notorite#1]
![image](https://github.com/user-attachments/assets/08ec2b60-fea9-4802-8243-f6202fb75630)
![image](https://github.com/user-attachments/assets/e3b7aa26-060e-4c03-b93c-ba746719a8bf)

This is the profile page. Improvements needed:
1. Add Life into it. Make it more attractive and dynamic.
2. Adjust Profile Picture inside Circle. Make it dynamic such that user can crop and edit image anytime.
3. Add 'EDIT' Button
4. Make the Vertical Line moveable such that user can split profile and documents lists.
5. Make background color of each shared documents different, such that look great. You can make it full width.

**Comment by roiveredritesh** [comment]
@manjit-hub I would like to take this issue for hacktoberfest

**Comment by jenyyy4** [comment]
@manjit-hub I would like to work on this issue, please assign it to me.

**Comment by roiveredritesh** [comment]
@manjit-hub Could you please add hacktoberfest label in this issue?

**Comment by mjkoder** [comment]
@roiveredritesh what's the status ?

**Comment by roiveredritesh** [comment]
@manjit-hub I am working on this, I will raise PR on Saturday.

**Comment by mjkoder** [comment]
@roiveredritesh it's already Sunday !!

**Comment by roiveredritesh** [comment]
@manjit-hub If you want you can assign this to any other person.
