### ISSUE TITLE
Init Shadcn UI

### ISSUE THREAD

**Issue by rahulxdemon** [manjit-hub/Notorite#14]
I would like to add Shadcn UI and add a dark mode to app

**Comment by mjkoder** [comment]
Great !! Try making dynamic.

**Comment by rahulxdemon** [comment]
I will start working on it

**Comment by rahulxdemon** [comment]
@manjit-hub I have initialized Shadcn ui, but didn't add dark mode because there already a PR made by @anuj-pal27

**Comment by rahulxdemon** [comment]
@manjit-hub Here is a PR for this feature #19

**Comment by mjkoder** [comment]
have you added toggle button at top. Can you please share some screenshorts

**Comment by rahulxdemon** [comment]
Right now I didn't add any toggle button

Should I add toggle button ??

**Comment by mjkoder** [comment]
Yes it's important to add a toggle button.

**Comment by rahulxdemon** [comment]
Ok I will add the toggle button

**Comment by rahulxdemon** [comment]
@manjit-hub here is the ss of the theme toggle button

![image](https://github.com/user-attachments/assets/d37cf45e-a94a-4b07-bf1f-d8f8103516f5)

![image](https://github.com/user-attachments/assets/ace6646b-d912-4991-9c7c-3bc71d8e9d69)

**Comment by mjkoder** [comment]
@rahulpeacock  Can you make it bit different. Such that upon clicking it will automatically switch to next theme without showing theme dropdown. And 'System' is not needed. By default make it dark.

**Comment by rahulxdemon** [comment]
Ok I will change it

**Comment by rahulxdemon** [comment]
@manjit-hub I have completed the feature and made a PR #19
