### ISSUE TITLE
change-styling

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [manjit-hub/Notorite#16]
the color combination used to create the whole website its quite not looking well and the form those you are created 
![Notorite _ Share Your Notes - Google Chrome 02-10-2024 10_06_14 AM](https://github.com/user-attachments/assets/bcd8c9bc-868a-4351-aa55-8fbb6d53d915)

**Comment by mjkoder** [comment]
Yes, I have already added that issue in previous issues. You can check it out, also contribute collaboarately.
