### ISSUE TITLE
about page

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [manjit-hub/Notorite#17]
in the about page there is just some paragraph writing thats it so i want to improve that
assign me  this task with hactoberfest tag.

**Comment by Mukesh-ghildiyal** [comment]
![Uploading github.com - Google Chrome 02-10-2024 10_20_20 AM.png…]()

**Comment by mjkoder** [comment]
Can you make it dynamic which matches our theme and objectives. Also can you add contributors github profile hyperlinks at the end of about page?

**Comment by Mukesh-ghildiyal** [comment]
Sure 👍
