### ISSUE TITLE
Signup not working on server side

### ISSUE THREAD

**Issue by thefuadeniola** [manjit-hub/Notorite#20]
Ran into a few issues on signing up, had to restyle a bit to see the form properly. After running the server and trying to signup, it kept throwing a 500 because it couldn't find the image filepath in the signup logic. Adding an image folder might have solved that, but now I receive a 403. It keeps saying unexpected server error. Currently looking into that so I can see the rest of the application.

**Comment by mjkoder** [comment]
can you please check your 'server' side setup and make sure that added 'env' file properly. Because it's working properly in deployed server. Also try to trace the error codes.
