### ISSUE TITLE
Server-side Logic

### ISSUE THREAD

**Issue by Bluesparx** [manjit-hub/Notorite#22]
There are several issues related to how we're handling sign-up.
Also, the mobile number isn't really required we should remove it from user Model. 

# Issues
The current setup appears to incorrectly reference files in the local working directory instead of handling uploads directly to Cloudinary. Attached ss for clarity
![Screenshot 2024-10-02 124914](https://github.com/user-attachments/assets/66dc9aeb-cc0d-4293-af00-81e88ec3dd24)

**Comment by mjkoder** [comment]
can you also add verification mail feature while sign up. 
Why do you think phone number is not required?

**Comment by Bluesparx** [comment]
Verification mail sounds good, we will need a sender mail for that? I'm not sure how to implement mails might look into it later..

As for the phone no part, I believe the reason we're using the mail is to authenticate and contact the user by sending mails. It's very rare that we receive sms notifs from websites. There are privacy concerns as well.

**Comment by mjkoder** [comment]
ok great then update user schema too,
If you can work on verification part then fine. Otherwise I will do or assign to someone else.

**Comment by Dhruv80576** [comment]
@manjit-hub 
I would like to work on verification mail.
