### ISSUE TITLE
Adding a mouse follower

### ISSUE THREAD

**Issue by Speedysays01** [manjit-hub/Notorite#27]
A minimalistic mouse follower could be a great enhancement to the UI.
Please assign me this issue under Hacktoberfest2024

**Comment by mjkoder** [comment]
please share ss after changes before pr

**Comment by vanshchauhan1310** [comment]
please assign me this issue

**Comment by mjkoder** [comment]
hey @vanshchauhan1310 I think @Speedysays01 has already been assigned. So if he will not do then I will assign you in 1-2 days. Till then keep hunting issues.

**Comment by Speedysays01** [comment]
How does this look? (The mouse follower is near the sign-up button) Should I create a PR? if yes, please add a tag of Hacktoberfest to the issue.

**Comment by Speedysays01** [comment]
![Screenshot (171)](https://github.com/user-attachments/assets/e329cf84-00f4-43a1-ae92-92b88e177191)

**Comment by mjkoder** [comment]
I think you can make something better. eye-catching and smooth transitions. This seems quite simple and static. Add animations/effects to it.

**Comment by vanshchauhan1310** [comment]
> hey @vanshchauhan1310 I think @Speedysays01 has already been assigned. So if he will not do then I will assign you in 1-2 days. Till then keep hunting issues.

ok

**Comment by Speedysays01** [comment]
@manjit-hub ya sure I'll make something more catchy! I kept it simple because it's generally preferred that way. I'm glad that I'll get to use some creativity here.
