### ISSUE TITLE
Making the links react to hover

### ISSUE THREAD

**Issue by Speedysays01** [manjit-hub/Notorite#28]
Making the links in footer interactive to hover to enhance the UX.
Please assign me this issue under Hacktoberfest2024

**Comment by mjkoder** [comment]
do it, and do share screen shots before pr.

**Comment by Speedysays01** [comment]
I have added a subtle color change on hover to the links. Should I make a PR now? Here the mouse hover is on helpnotoroite@gmail.com
![Screenshot (169)](https://github.com/user-attachments/assets/dc4c1815-aa41-42f8-b74c-e753a903551e)
