### ISSUE TITLE
Improve SignUp page

### ISSUE THREAD

**Issue by mjkoder** [manjit-hub/Notorite#3]
![image](https://github.com/user-attachments/assets/54c176c5-e6e2-4b28-a065-1359b2067d66)
![image](https://github.com/user-attachments/assets/54c176c5-e6e2-4b28-a065-1359b2067d66)

1. Combine Both upload picture and circle.
2. add functionality that user can adjust the image fit on circle.
3. Improve over all color patterns.
4. Any extra improvements are always welcome

**Comment by Sahil-Gupta584** [comment]
@manjit-hub  i will solve this issue you can assign it to me

**Comment by jenyyy4** [comment]
@manjit-hub I would like to work on this issue, please assign it to me.

**Comment by Piiyush01** [comment]
@manjit-hub I would like to work on this issue. Since @Sahil-Gupta584 is already assigned, if you don't mind i want to Collab on this issue.
I am already working on a chat web app, So I have done similar work (UI related) in the past.

**Comment by ayush-848** [comment]
@manjit-hub I want to redesign the form part like its padding,styling, etc
May I collaborate with them??

**Comment by mjkoder** [comment]
@ayush-848 This part is already assigned to two contributors. So may be you should try on some new issues. Please find issues which are not yet raised and you think can contribute to it.
