### ISSUE TITLE
Not able to upload files | Configuring Docker into your project

### ISSUE THREAD

**Issue by TheAdich** [manjit-hub/Notorite#31]
Hi @manjit-hub,

I recently came across an issue when clicking on the "Upload PDF" button, which results in the following error (please see the attached screenshot). Based on my initial investigation, it seems to be a CORS policy issue. This likely means that we haven't configured the headers properly in the API.

![Screenshot 2024-10-03 012931](https://github.com/user-attachments/assets/31d296ae-9427-4d2c-9e4f-83001de17278)

Since it's an open-source project, I would like to contribute by configuring Docker for the project. This would provide the following benefits:

1.Streamlined Environment Setup: With Docker, other contributors can easily set up the project environment without dealing with potential configuration issues, making onboarding 

2.Cloudinary and Database Configuration: Docker will help handle all external service configurations (such as Cloudinary and the database), reducing potential issues contributors might face when connecting to these services.

3.Scalability and Portability: Docker will make the project more scalable and ensure consistency across different environments (development, testing, and production).

I have an experience in working with docker and will help you to configure this devops tool to your project.

If any of these improvements sound good to you, I would love to contribute and set up the Docker configuration as quickly as possible. Please feel free to assign this issue to me.

Looking forward to your response!

**Comment by mjkoder** [comment]
hey @TheAdich , for the moment I have assigned 'upload' part to someone else. And about docker part, it would be better if we will do that at very end of the project. As now we are doing repeated changes we have to constantly update the conatiners. Also it's not yet at that level to do paid containerization. So for the moment we will not work on it. But good idea !!
