### ISSUE TITLE
FAQS page UI Improvement needed

### ISSUE THREAD

**Issue by Riddhi050803** [manjit-hub/Notorite#33]
![image](https://github.com/user-attachments/assets/d94b21bb-6b0e-460c-864a-2bdac084863e)
The current UI of the FAQ page does not provide a good user experience. The layout and design feel cluttered and difficult to navigate. Some specific issues include poor spacing between questions, inconsistent font sizes, and a lack of visual hierarchy.

**Comment by Riddhi050803** [comment]
Please assign it to me @manjit-hub 
I want to make these changes:
UI Enhancements: Revamp the overall layout with a more modern design, improving the structure for better readability and user interaction.
Colors: Introduce a more appealing color palette that enhances readability, aligns with the overall design theme, and improves contrast between text and background.
Collapsible Sections: Implement collapsible sections for each FAQ item. This will allow users to expand and collapse questions, reducing the amount of information displayed at once and improving page navigation.
Animations: Add smooth transitions and animations when users open or close a question. This will enhance the user experience by making interactions feel more fluid and engaging.

**Comment by mjkoder** [comment]
hey @Riddhi050803. I think this part is also resolved by @Shivansh-0403. Please update your forked repo and analyze what better changes you can make on it or you can work on something else.

**Comment by parth-1372** [comment]
Hey @Riddhi050803 I want to Work on This issue If it is Still Not resolved.
