### ISSUE TITLE
Email Verification functionality

### ISSUE THREAD

**Issue by mjkoder** [manjit-hub/Notorite#35]
1. Add OTP verification while sign up to Email
2. Open link to verify - Email [Secondary it might be difficult then OTP system]
3. Dont use hard coded sender email. User env where owner/comapny email will be present

Update Signup page accordingly where 'send otp' button will be there and another text-box will be there where user will enter OTP. User data will only be created if he/she enters correct OTP.

**Comment by GaneshLadaskar** [comment]
Hii,
I am new in the world of open source but new to the text tack that you need so I can help you to resolve your issue so please assign me the issue.
Thank You!

**Comment by pulkitgxrg** [comment]
Hi @manjit-hub, I can create OTP verfication system where user data will only be accepted if user enters the correct OTP otherwise user will not be created in the database.

I can work on this assign, please assign me this issue.

**Comment by mjkoder** [comment]
@pulkitgarg04 assigned. Make sure that email used to send mail should be fetched from 'env' file and make a beautiful and attractive OTP mail.
