### ISSUE TITLE
User can change profile pic in profile section

### ISSUE THREAD

**Issue by ayush-848** [manjit-hub/Notorite#37]
User can change profile pic in profile section

**Comment by ayush-848** [comment]
@manjit-hub if you want this feature you can assign this issue to me

**Comment by mjkoder** [comment]
Profile Page Issue has been alloted to someone. After he/she completed that, we can proceed forward for this Edit Profile Picture feature. I will raise issue when it will be ready.

**Comment by ayush-848** [comment]
> Profile Page Issue has been alloted to someone. After he/she completed that, we can proceed forward for this Edit Profile Picture feature. I will raise issue when it will be ready.

Ok sure

**Comment by mjkoder** [comment]
@ayush-848 can you work on it ??
Also:
1. In latest version, we can not resize, crop, edit profile picture.
2. So we have to add a feature such that User can do all these things while sign ups and add his/ her dp. 
3. User can also modify/update his dp from profile page too.

**Comment by ayush-848** [comment]
> @ayush-848 can you work on it ?? Also:
> 
> 1. In latest version, we can not resize, crop, edit profile picture.
> 2. So we have to add a feature such that User can do all these things while sign ups and add his/ her dp.
> 3. User can also modify/update his dp from profile page too.

I can give it a shot
