### ISSUE TITLE
Improve UI of Serach Page

### ISSUE THREAD

**Issue by mjkoder** [manjit-hub/Notorite#4]
![image](https://github.com/user-attachments/assets/1173a337-026a-48de-b4a1-bdb62796c642)
1. Make it dynamic.
2. Display all files uploaded in database to display here in any order.
3. You can also add filter functionality.
4. Make it dynamic
5. Any extra idea and features are always welcome

**Comment by ishaan-coder** [comment]
Hi Can you please assign me this issue I will make the search bar dynamic and also add filter functionality and will also display all files. I think I can also add new features also.

**Comment by jenyyy4** [comment]
@manjit-hub I would like to work on this issue, please assign it to me.

**Comment by mjkoder** [comment]
@ishaan-coder what's the update ??

**Comment by mjkoder** [comment]
@jenyyy4 would you like to work on this ?
