### ISSUE TITLE
Forgot password functionality while login

### ISSUE THREAD

**Issue by pulkitgxrg** [manjit-hub/Notorite#42]
Hi @manjit-hub, There should be a forgot password functionality in the login section so that user can reset password with their mail. I can work on this, can you please assign me this issue.

**Comment by mjkoder** [comment]
goog issue. Make sure user can use forget password by verifying his gmail. Like OTP or hyperlink sent to his/her mail.

**Comment by pulkitgxrg** [comment]
So, I can proceed with this issue? Could you please assign me this issue.
