### ISSUE TITLE
Frontend (API) Request Handler

### ISSUE THREAD

**Issue by Bluesparx** [manjit-hub/Notorite#43]
### Create api/apiRequest.js file in the frontend src directory
Implement functions in apirequest.js to interact with backend API:

1. Use fetch/axios for making HTTP requests
2. Create functions for each API endpoint

**Comment by mjkoder** [comment]
Can you please explain about the things you will work on and how it will work?? @Bluesparx

**Comment by shubham7522** [comment]
Hello , I am Shubham , i am new to open source 
can u please assign me this issue?

**Comment by mjkoder** [comment]
@shubham7522 go for it.

**Comment by shubham7522** [comment]
#65
