### ISSUE TITLE
Improve Logo UI 

### ISSUE THREAD

**Issue by mjkoder** [manjit-hub/Notorite#5]
![image](https://github.com/user-attachments/assets/e4f91af8-41fb-4d25-9fbd-96a8f7254613)
1. Suggest some new creative and dynamic logo.
2. Add logo click functionality. Such that whenever user will click on logo, he/she will be redirected to home page.
3. Extra innovative ideas are always welcome

**Comment by Shreyashahu** [comment]
I can help you out with this, just assign it to me.

**Comment by jenyyy4** [comment]
@manjit-hub I would like to work on this issue, please assign it to me.

**Comment by anuj-pal27** [comment]
@manjit-hub i had add the logo click functionality please review my pull requrest

**Comment by Shreyashahu** [comment]
I am half way there, can you add the hacktoberfest label to this issue?

**Comment by shreyajaiswal17** [comment]
@manjit-hub I would like to work on this

**Comment by mjkoder** [comment]
@Shreyashahu what is the update on logo part ??

**Comment by mjkoder** [comment]
@shreyajaiswal17 would you like to work on this ?

**Comment by shreyajaiswal17** [comment]
Yess !

**Comment by shreyajaiswal17** [comment]
@manjit-hub  ![Screenshot 2024-10-07 191652](https://github.com/user-attachments/assets/4c23e152-99e7-42f9-851a-efe498c4cc31)

![Screenshot 2024-10-07 190310](https://github.com/user-attachments/assets/695bd9b5-acb2-4019-9613-c2b0ff54ffb4)

any one you liked ? or should I work further?

**Comment by mjkoder** [comment]
@shreyajaiswal17 1st one seems cool. Can you add it's transparent png with already existing logo. Also make sure it looks great with both themes. Make sure that pixel quality of png is good, such that It does not break while loading in big screen. Do share the final logo before making pr. Along with adjust the header.

**Comment by mjkoder** [comment]
![image](https://github.com/user-attachments/assets/3f2e6732-ed45-4304-8ef7-c1b54b48d0d8)
This one.

**Comment by shreyajaiswal17** [comment]
![Screenshot_2024-10-07_191213-removebg-preview](https://github.com/user-attachments/assets/c2a2154f-ce84-4192-87d2-87b45dad261e)

**Comment by shreyajaiswal17** [comment]
have opened the PR kindly merge it.
