### ISSUE TITLE
Forgot Password Link Not Working

### ISSUE THREAD

**Issue by mohit-1710** [manjit-hub/Notorite#58]
### Issue:
When trying to reset the password through the "Forgot Password" feature, the link provided in the reset email is leading to a **404 Page Not Found** error.

### Steps to Reproduce:
1. Navigate to the **Login** page.
2. Click on the **Forgot Password** option.
3. Enter your registered email address.
4. Receive an email with a password reset link.
5. Click on the link in the email.
6. The page that loads shows a **404 Page Not Found** error instead of the password reset page.

### Expected Behavior:
- Upon clicking the password reset link, the user should be redirected to a functional password reset page to create a new password.

### Actual Behavior:
- The user is instead redirected to a **404 Page Not Found** error page.

### Possible Causes:
- The reset link might be broken or not pointing to the correct URL.
- The backend might be misconfigured, leading to the missing reset page.
- The route for the password reset page might not exist or might have been deleted.

### Suggested Fix:
- Ensure that the reset link generated in the email points to the correct URL.
- Check the routing and server configuration for handling password resets.
- Ensure the reset page exists and is properly accessible on the server.

### Screenshot:
![WhatsApp Image 2024-10-07 at 22 42 19_10962f03](https://github.com/user-attachments/assets/5b8bf158-d9ee-49a9-8aa0-fb28aa7bf7ec)

**Comment by mohit-1710** [comment]
@manjit-hub  please assign this issue to me .

**Comment by mjkoder** [comment]
@mohit-1710 assigned
