### ISSUE TITLE
Add transition to HomePage

### ISSUE THREAD

**Issue by mjkoder** [manjit-hub/Notorite#6]
![image](https://github.com/user-attachments/assets/37b39e79-31ad-4c2c-996d-84e83fce2394)
1. Add transition to home page. 
2. If have better idea then replace bg image with some better gradients color pallets[make sure it matched overall theme and style]
3. Any extra innovative idea are always welcome

**Comment by jenyyy4** [comment]
@manjit-hub I would like to work on this issue, please assign it to me.

**Comment by Piiyush01** [comment]
@manjit-hub I would like to work on this , kindly Assign this to me

**Comment by mjkoder** [comment]
Any update ?? I will add hactoberfest label if you put good work.
