### ISSUE TITLE
Feature Request: Enhanced Mobile Number Input with Country Code Selector and Validation

### ISSUE THREAD

**Issue by Krishna3451** [manjit-hub/Notorite#60]
## Overview
The current registration form's mobile number input field needs enhancement to improve user experience and data validation. This feature request suggests adding an improved country code selector and enforcing a 10-digit validation for mobile numbers to ensure correct formatting and consistency.

## Problem
- The existing mobile number field lacks a robust country code selector, which might confuse users from different regions.
- There is no strict validation on the number of digits entered, leading to potential data inconsistency and incorrect input (i.e., numbers that are too short or too long).

## Proposed Solution
1. **Improved Country Code Selector**:
   - Implement a user-friendly country code selector dropdown that allows users to select their country and automatically appends the respective country code.
   - Include flags for visual identification and support search functionality to make selection faster.

2. **Mobile Number Validation**:
   - Enforce a validation rule that only allows users to enter exactly 10 digits in the mobile number input field (not including the country code).
   - Display a warning message if the input is shorter or longer than 10 digits, prompting the user to correct it.
## Benefits
- **Improved User Experience**: A more intuitive country code selector and validation check will guide users in providing correct and standardized contact information.
## Screenshots
Original:
![image](https://github.com/user-attachments/assets/5fc9e52e-c949-417c-bef1-8b5fdd04b98a)
Feature Idea:
![image](https://github.com/user-attachments/assets/68f3dfb1-75ad-4477-abd1-982fb6f66493)

**Comment by Krishna3451** [comment]
@manjit-hub I would like to work on this feature.

**Comment by mjkoder** [comment]
Actually we hve decided that we will remove mobile number section because it has no use for the moment.
