### ISSUE TITLE
Add a theme change togle 

### ISSUE THREAD

**Issue by mjkoder** [manjit-hub/Notorite#7]
1.Add a theme change togle to website. Currently it only have dark theme.
2. Add a light theme UI
3. Add a toggle button at top.

**Comment by Shreyashahu** [comment]
I can do this if you assign it to me.

**Comment by jenyyy4** [comment]
@manjit-hub I would like to work on this issue, please assign it to me.

**Comment by Piiyush01** [comment]
@manjit-hub We can use context API to handle light/dark mode switching. For the light theme UI. we can add the toggle button at the top of the page, So kindly assign this issue to me i will get it done

**Comment by anuj-pal27** [comment]
@manjit-hub  i had added the theme that you mentioned above there is toggle button and also added a new feature in UI . please review my pull request that i have made

**Comment by mjkoder** [comment]
@anuj-pal27 you better ask for assign. Otherwise it would be unfair for other contributors.

**Comment by anuj-pal27** [comment]
sorry @manjit-hub currently i am a beginner . i will take care of this

**Comment by anuj-pal27** [comment]
can you assign this to me i had already made a pull requrest on this issue.

**Comment by mjkoder** [comment]
@anuj-pal27 
I think this part is already done. You can check out for new issues in differenet pages. Do raise an issue. I will assign you.

**Comment by Shivansh-0403** [comment]
Could you please assign this issue to me. I have added light theme css and toggle button.
