### ISSUE TITLE
layout issue: Mobile view need to be fixed

### ISSUE THREAD

**Issue by Satvik1769** [manjit-hub/Notorite#73]
Layout of profile page is needed to be fixed

**Comment by mjkoder** [comment]
@Satvik1769 can you express what changes you are thinking of ? with ss

**Comment by Satvik1769** [comment]
this!!!


![image](https://github.com/user-attachments/assets/6c7ef3ca-e057-479f-97a0-9330b907e265)

**Comment by mjkoder** [comment]
Can you also work on each page and make every page responsive according to the resolution?? Also fix profile page. Make it theme responsive.

**Comment by Satvik1769** [comment]
other pages don't have issue this page is having a bit of issue. It can be done . I was thinking to let others take this issue as it is a great good first issue.
